on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    env:
      ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TENANT_ID}}
    name: "Terraform Deploy"
    run-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/cicd
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: terraform init
      id: init
      run: terraform init
    
    # Check format
    - name: Terraform Format Check
      id: check
      run: terraform fmt -check

    # Valida configuraciones
    - name: Terraform Validate
      id: validate
      run: terraform validate

    # Plan (simulación de cambios)
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    # Apply automático SOLO en main
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
